version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform.zip && mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform validate
      - terraform plan

  post_build:
    commands:
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
